
export const GET_WALLET_ADDRESS = "GET_WALLET_ADDRESS";
export const GET_USER_THB_BALANCE ="GET_USER_THB_BALANCE"
export const GET_USER_THB_LP_BALANCE ="GET_USER_THB_LP_BALANCE"
export const GET_USER_TAMOUNT ="GET_USER_TAMOUNT"
export const GET_USER_TAMOUNT_LP ="GET_USER_TAMOUNT_LP"
export const GET_USER_BRL ="GET_USER_BRL"
export const  GET_USER_BRL_LP ="GET_USER_BRL_LP"
export const GET_USER_MINT_BRAWL_POINTS ="GET_USER_MINT_BRAWL_POINTS"
export const GET_CURRENT_BP_TOKENS ="GET_CURRENT_BP_TOKENS"
export const GET_MAX_BP_TOKENS="GET_MAX_BP_TOKENS"
export const LP_LOCK_TIME = "LP_LOCK_TIME"
export const USER_DEPOSIT_TIME ="USER_DEPOSIT_TIME"
